In [18]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor

import statsmodels.formula.api as sm
from sklearn.model_selection import cross_val_score

%matplotlib inline

In [19]:
building = pd.read_csv('data/com.csv')
building.head()

,ptype,floora_plan,year,occ,es,site_EUI,n_site_gas,n_site_elec,water_use
0,Multifamily,412503.0,1903,100,93,32.0,20472.0,3249755.2,22061.0
1,General Medical,567517.0,1950,100,80,352.7,1255514.1,18295844.6,9574.0
2,Multifamily,321464.0,1939,100,72,76.2,8906.3,1121931.8,5915.6
3,Multifamily,54913.0,1911,100,100,17.9,601.0,262377.2,231.9
4,Multifamily,175885.0,1973,100,40,56.2,39028.3,1887619.4,237.9

In [20]:
x_columns = ['ptype', 'floora_plan', 'year', 'occ', 'es', 'n_site_gas', 'n_site_elec', 'water_use']
y_columns = ['site_EUI']
# X = building[x_columns]
# y = building[y_columns]
X = pd.get_dummies(building[x_columns],drop_first=True)
y = building[y_columns]

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [22]:
from sklearn import preprocessing
mm_scaler = preprocessing.MinMaxScaler()
X_train_minmax = mm_scaler.fit_transform(X_train)
mm_scaler.transform(X_test)

C:\Users\37102\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)

array([[0.02234575, 0.74324324, 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.02085969, 0.85135135, 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.02362748, 0.90810811, 1.        , ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.02026443, 0.73783784, 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.4658441 , 0.75405405, 1.        , ..., 1.        , 0.        ,
        0.        ],
       [0.14107417, 0.76486486, 1.        , ..., 1.        , 0.        ,
        0.        ]])

In [23]:
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)
regressor.fit(X, y)

C:\Users\37102\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [24]:
y_prediction = regressor.predict(X_test)

In [33]:
pd.DataFrame(y_test).values.transpose()[0]
y_prediction

array([ 99.054,  95.978,  72.371, ..., 152.095,  67.83 ,  73.523])

In [26]:

pd.DataFrame({
    'Real' : pd.DataFrame(y_test).values.transpose()[0],
    'Predict' : y_prediction

})

       Real  Predict
0     100.4   99.054
1      95.6   95.978
2      72.8   72.371
3     100.6   95.967
4     114.1  108.344
5      76.3   77.162
6     107.4  104.501
7      72.6   72.627
8      62.7   64.561
9      88.7   88.681
10    102.9  101.428
11     62.7   61.886
12     77.8   75.546
13     96.0   99.143
14    114.3  113.973
15    437.9  387.071
16     80.6   81.007
17     66.5   69.201
18     29.0   50.098
19     76.3   75.893
20     99.4   96.433
21     72.2   71.984
22    108.2  103.639
23     92.3   88.562
24     67.7   68.676
25     51.9   53.065
26    111.9  109.812
27    102.0  100.649
28     64.4   66.180
29    131.7  129.826
...     ...      ...
1085   91.0   94.869
1086   35.3   32.033
1087   64.3   64.956
1088   59.6   58.484
1089   76.6   77.281
1090   72.4   75.785
1091   69.9   69.713
1092   68.5   67.831
1093  185.7  189.151
1094  116.0  113.296
1095   68.4   69.189
1096   68.3   68.692
1097   79.0   78.708
1098   27.2   28.882
1099   86.2   89.233
1100   82.6   89.701
1101   20.5   20.653
1102   77.0   76.563
1103  134.1  141.974
1104   75.7   71.088
1105   65.2   67.677
1106   41.8   46.024
1107   58.0   58.525
1108   59.6   63.460
1109   77.1   74.751
1110   60.5   66.251
1111   96.6   96.367
1112  154.8  152.095
1113   71.3   67.830
1114   72.2   73.523

[1115 rows x 2 columns]

In [27]:
print(f"Training Data Score: {regressor.score(X_train, y_train)}")
print(f"Testing Data Score: {regressor.score(X_test, y_test)}")

Training Data Score: 0.8690920485619001
Testing Data Score: -0.77503883278138

In [28]:
accuracies = cross_val_score(estimator = regressor, X = X_train, y = y_train, cv = 10)

C:\Users\37102\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\37102\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\37102\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\37102\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\37102\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\37102\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\37102\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\37102\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\37102\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\37102\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

In [29]:
print (accuracies)

[-3.19989229e+03 -1.61118565e+00  9.84767323e-01 -1.38877262e+00
  7.94564102e-02 -3.02177829e-01  2.62611508e-03 -3.16930802e+01
 -1.77837571e+01 -1.29857235e-03]

In [30]:
accuracies.mean()

-325.16057126619637

In [31]:
accuracies.std()

958.2976054018505