# Exponential Smoothing
____

#### Libraries
____

In [32]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from statsmodels.tsa.api import ExponentialSmoothing, SimpleExpSmoothing, Holt


%matplotlib inline

#### Load dataset
___

In [36]:
dataset = '../../../Greenhouse/data/US_emissions_by_gas_1990_2017_data.xlsx'

emissions = pd.read_excel(dataset)
emissions.head(5)

,Gas,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Carbon dioxide,5121.179440,5071.563914,5174.670601,5281.386608,5375.033803,5436.697986,5625.041885,5701.920919,5749.893056,...,5928.256329,5493.547908,5700.108337,5572.584775,5371.777170,5522.908365,5572.106312,5422.965677,5306.662457,5270.748525
1,Methane,779.845550,784.384856,783.176602,770.308404,775.160651,767.845344,759.491158,744.932926,729.618317,...,702.303384,692.676127,697.450404,675.544902,665.372404,663.042641,662.064221,661.395920,654.897884,656.316679
2,Nitrous oxide,370.307694,368.961757,371.786442,385.347234,376.511527,388.502830,395.545749,386.608376,402.495771,...,374.546556,373.259958,382.929378,375.073815,348.876128,365.354277,362.742736,374.108885,364.485759,360.515661
3,Fluorinated gases,99.667859,90.704668,95.300712,95.027350,98.129806,117.021137,127.620262,134.999750,150.518866,...,155.494544,149.885151,158.103563,164.215536,159.943630,158.912892,163.082364,165.304997,166.221325,169.137327
4,Total,6371.000543,6315.615194,6424.934357,6532.069596,6624.835787,6710.067297,6907.699054,6968.461971,7032.526010,...,7160.600813,6709.369145,6938.591681,6787.419028,6545.969331,6710.218175,6759.995633,6623.775479,6492.267425,6456.718193

In [37]:
cond1 = emissions['Gas'] == 'Methane'
emission = emissions[cond1] 
emissions.set_index('Gas', inplace=True)

In [30]:
emissions

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
Gas,,,,,,,,,,,,,,,,,,,,,
Carbon dioxide,5121.179440,5071.563914,5174.670601,5281.386608,5375.033803,5436.697986,5625.041885,5701.920919,5749.893056,5829.519951,...,5928.256329,5493.547908,5700.108337,5572.584775,5371.777170,5522.908365,5572.106312,5422.965677,5306.662457,5270.748525
Methane,779.845550,784.384856,783.176602,770.308404,775.160651,767.845344,759.491158,744.932926,729.618317,717.451035,...,702.303384,692.676127,697.450404,675.544902,665.372404,663.042641,662.064221,661.395920,654.897884,656.316679
Nitrous oxide,370.307694,368.961757,371.786442,385.347234,376.511527,388.502830,395.545749,386.608376,402.495771,377.091249,...,374.546556,373.259958,382.929378,375.073815,348.876128,365.354277,362.742736,374.108885,364.485759,360.515661
Fluorinated gases,99.667859,90.704668,95.300712,95.027350,98.129806,117.021137,127.620262,134.999750,150.518866,147.399221,...,155.494544,149.885151,158.103563,164.215536,159.943630,158.912892,163.082364,165.304997,166.221325,169.137327
Total,6371.000543,6315.615194,6424.934357,6532.069596,6624.835787,6710.067297,6907.699054,6968.461971,7032.526010,7071.461457,...,7160.600813,6709.369145,6938.591681,6787.419028,6545.969331,6710.218175,6759.995633,6623.775479,6492.267425,6456.718193

In [43]:
emissions.unstack(level=1)

      Gas
1990  Carbon dioxide       5121.179440
      Methane               779.845550
      Nitrous oxide         370.307694
      Fluorinated gases      99.667859
      Total                6371.000543
1991  Carbon dioxide       5071.563914
      Methane               784.384856
      Nitrous oxide         368.961757
      Fluorinated gases      90.704668
      Total                6315.615194
1992  Carbon dioxide       5174.670601
      Methane               783.176602
      Nitrous oxide         371.786442
      Fluorinated gases      95.300712
      Total                6424.934357
1993  Carbon dioxide       5281.386608
      Methane               770.308404
      Nitrous oxide         385.347234
      Fluorinated gases      95.027350
      Total                6532.069596
1994  Carbon dioxide       5375.033803
      Methane               775.160651
      Nitrous oxide         376.511527
      Fluorinated gases      98.129806
      Total                6624.835787
1995  Carbon dioxide       5436.697986
      Methane               767.845344
      Nitrous oxide         388.502830
      Fluorinated gases     117.021137
      Total                6710.067297
                              ...
2012  Carbon dioxide       5371.777170
      Methane               665.372404
      Nitrous oxide         348.876128
      Fluorinated gases     159.943630
      Total                6545.969331
2013  Carbon dioxide       5522.908365
      Methane               663.042641
      Nitrous oxide         365.354277
      Fluorinated gases     158.912892
      Total                6710.218175
2014  Carbon dioxide       5572.106312
      Methane               662.064221
      Nitrous oxide         362.742736
      Fluorinated gases     163.082364
      Total                6759.995633
2015  Carbon dioxide       5422.965677
      Methane               661.395920
      Nitrous oxide         374.108885
      Fluorinated gases     165.304997
      Total                6623.775479
2016  Carbon dioxide       5306.662457
      Methane               654.897884
      Nitrous oxide         364.485759
      Fluorinated gases     166.221325
      Total                6492.267425
2017  Carbon dioxide       5270.748525
      Methane               656.316679
      Nitrous oxide         360.515661
      Fluorinated gases     169.137327
      Total                6456.718193
Length: 140, dtype: float64